// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetProcesses():Promise<types.Response>;

export function TerminateProcess(arg1:number):Promise<types.Response>;
