// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function TerminateProcess(arg1) {
  return window['go']['main']['App']['TerminateProcess'](arg1);
}
